import { StyleSheet } from 'react-native';
import { colors, fontSize, fonts, layout, radius } from '../../../theme';
import { TRANSFER_PANEL_BG } from './constants';

export const transferRequestStyles = StyleSheet.create({
  flex: { flex: 1, backgroundColor: colors.soft },
  embeddedRoot: {
    backgroundColor: TRANSFER_PANEL_BG,
  },
  errorText: { fontSize: fontSize.mdLg, color: colors.muted, textAlign: 'center', lineHeight: 23 },
  retryWrap: { width: '100%', maxWidth: 220 },

  summary: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingHorizontal: layout.screenPadding,
    paddingTop: 14,
    paddingBottom: 16,
    backgroundColor: colors.canvas,
    borderBottomWidth: 1,
    borderBottomColor: colors.hairline,
  },
  embeddedSummary: {
    marginHorizontal: 16,
    marginTop: 8,
    borderRadius: 20,
    borderBottomWidth: 0,
    backgroundColor: colors.white,
    shadowColor: '#AAB2C0',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.05,
    shadowRadius: 18,
    elevation: 2,
  },
  summaryText: { flex: 1, gap: 4 },
  summaryActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  refreshButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.brandSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  summaryTitle: {
    fontFamily: fonts.semibold,
    fontSize: fontSize.base,
    color: '#707070',
    letterSpacing: -0.1,
  },
  summarySub: {
    fontFamily: fonts.regular,
    fontSize: fontSize.sm,
    lineHeight: 20,
    color: '#8A8A8A',
  },
  pendingBadge: {
    width: 58,
    height: 58,
    borderRadius: 18,
    backgroundColor: colors.brandSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pendingCount: { fontFamily: fonts.bold, fontSize: fontSize['2xl'], color: colors.brand },
  pendingLabel: { fontFamily: fonts.semibold, fontSize: fontSize.micro, color: colors.brand },

  listPanel: {
    flex: 1,
    marginHorizontal: 16,
    backgroundColor: colors.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    shadowColor: '#AAB2C0',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.05,
    shadowRadius: 18,
    elevation: 2,
    overflow: 'hidden',
  },
  listPanelEmbedded: {
    marginTop: 10,
    marginBottom: 0,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  tabWrap: {
    width: '100%',
  },
  tabWrapBorder: {
    borderBottomWidth: 1,
    borderBottomColor: '#ECECEC',
  },
  segmentedControl: {
    flexDirection: 'row',
    width: '100%',
  },
  segment: {
    flex: 1,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  segmentActive: {
    backgroundColor: colors.brandActive,
  },
  segmentInactive: {
    backgroundColor: 'transparent',
  },
  segmentPressed: {
    opacity: 0.88,
  },
  segmentText: {
    fontFamily: fonts.medium,
    fontSize: fontSize.sm,
    color: colors.muted,
    textAlign: 'center',
  },
  segmentTextActive: {
    fontFamily: fonts.semibold,
    color: colors.white,
  },
  segmentCount: {
    fontFamily: fonts.bold,
    fontSize: fontSize.sm,
    color: colors.muted,
  },
  segmentCountActive: {
    color: colors.white,
  },
  filterSection: {
    width: '100%',
  },
  filterDivider: {
    height: 1,
    backgroundColor: '#ECECEC',
  },
  filterInner: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 10,
  },
  filterRowWrap: {
    flexDirection: 'row',
    gap: 6,
  },
  filterChip: {
    flex: 1,
    borderRadius: 8,
    backgroundColor: '#F4F5F8',
    paddingHorizontal: 4,
    paddingVertical: 5,
    minHeight: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterChipActive: {
    backgroundColor: colors.brandSoft,
  },
  filterChipText: {
    fontFamily: fonts.medium,
    fontSize: fontSize.xs,
    color: '#8A8A8A',
  },
  filterChipTextActive: {
    fontFamily: fonts.semibold,
    color: colors.brand,
  },

  listArea: {
    flex: 1,
  },
  listAreaEmpty: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  listAreaCentered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 48,
    gap: 16,
  },
  listContent: {
    paddingBottom: 0,
  },
  listContentReceived: {
    paddingTop: 8,
  },
  emptyBox: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    paddingVertical: 24,
    gap: 8,
  },
  emptyIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#F1F1F3',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  emptyTitle: {
    fontFamily: fonts.semibold,
    fontSize: fontSize.base,
    color: '#111111',
    textAlign: 'center',
  },
  emptyText: {
    fontFamily: fonts.regular,
    fontSize: fontSize.sm,
    color: '#8A8A8A',
    textAlign: 'center',
    lineHeight: 20,
    maxWidth: 240,
  },

  requestCard: {
    paddingHorizontal: 22,
    paddingVertical: 20,
    gap: 12,
  },
  requestCardDivider: {
    borderTopWidth: 1,
    borderTopColor: '#ECECEC',
  },
  cardTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  statusBadge: {
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: '#F0F1F4',
  },
  statusBadgeDot: { width: 6, height: 6, borderRadius: 3 },
  statusBadgeText: {
    fontFamily: fonts.medium,
    fontSize: fontSize.sm,
    color: '#616778',
  },
  dateText: {
    fontFamily: fonts.regular,
    fontSize: fontSize.sm,
    color: '#8A8A8A',
    flexShrink: 0,
  },
  cardTitle: {
    fontFamily: fonts.bold,
    fontSize: fontSize.base,
    color: '#111111',
    lineHeight: 23,
  },
  deptRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  deptFrom: {
    flex: 1,
    minWidth: 0,
    fontFamily: fonts.regular,
    fontSize: fontSize.sm,
    color: '#8A8A8A',
  },
  deptTo: {
    flex: 1,
    minWidth: 0,
    fontFamily: fonts.medium,
    fontSize: fontSize.sm,
    color: '#111111',
  },
  reasonBox: {
    backgroundColor: TRANSFER_PANEL_BG,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 6,
  },
  reasonLabel: {
    fontFamily: fonts.medium,
    fontSize: fontSize.sm,
    color: '#8A8A8A',
  },
  reasonText: {
    fontFamily: fonts.regular,
    fontSize: fontSize.base,
    color: '#111111',
    lineHeight: 22,
  },
  metaLine: {
    fontFamily: fonts.regular,
    fontSize: fontSize.sm,
    color: '#8A8A8A',
    lineHeight: 20,
  },
  responseActions: { flexDirection: 'row', gap: 10, paddingTop: 4 },
  actionButton: { flex: 1 },

  sheetBody: { gap: 18 },
  sheetEyebrow: { fontFamily: fonts.bold, fontSize: fontSize.md, color: colors.brand },
  sheetTitle: {
    fontFamily: fonts.bold,
    fontSize: fontSize.xl,
    lineHeight: 26,
    color: colors.ink,
    marginTop: 4,
  },
  inputLabel: {
    fontFamily: fonts.semibold,
    fontSize: fontSize.md,
    color: colors.muted,
    marginBottom: 8,
  },
  reasonInput: {
    minHeight: 104,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.hairline,
    backgroundColor: colors.soft,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontFamily: fonts.regular,
    fontSize: fontSize.base,
    color: colors.ink,
  },
  reasonCounter: {
    marginTop: 6,
    textAlign: 'right',
    fontFamily: fonts.medium,
    fontSize: fontSize.xs,
    color: colors.faint,
  },
  reasonCounterLimit: {
    color: colors.danger,
  },
  sheetActions: { flexDirection: 'row', gap: 10 },
  sheetButton: { flex: 1 },
});
